### ISSUE TITLE
Invalida FASTQ ID

### ISSUE THREAD

**Issue by atks** [mgymrek/lobstr-code#51]
Hi Melissa,

I'm running lobSTR on 1000 Genomes NA12878 fastq files and I encountered a formatting error.  May you look into it?

The files are:

ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/data/NA12878/sequence_read/SRR000921_1.filt.fastq.gz
ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/data/NA12878/sequence_read/SRR000921_2.filt.fastq.gz

command:

../programs/lobSTR-3.0.2/bin/lobSTR --p1 /net/1000g/atks/data/NA12878/SRR000921_1.filt.fastq.gz  --p2 /net/1000g/atks/data/NA12878/SRR000921_2.filt.fastq.gz --index-prefix ../programs/lobSTR-3.0.2/resource/lobstr_v3.0.2_hg19_ref/lobSTR_ -o na12878 --rg-lib abc --rg-sample NA12878

I tried it with the non gzipped versions and the same error was encountered.

error:

[lobSTR-3.0.2] 2014-11-21.09:29:08 ProgressMeter: Getting run info
[lobSTR-3.0.2] 2014-11-21.09:29:08 ProgressMeter: Initializing...
[lobSTR-3.0.2] 2014-11-21.09:29:34 ProgressMeter: Running detection/alignment...
[lobSTR-3.0.2] 2014-11-21.09:29:34 ProgressMeter: Processing files /net/1000g/atks/data/NA12878/SRR000921_1.filt.fastq.gz and /net/1000g/atks/data/NA12878/SRR000921_2.filt.fastq.gz
[lobSTR-3.0.2] 2014-11-21.09:29:34 ERROR: Found Invalid FASTA ID in file /net/1000g/atks/data/NA12878/SRR000921_1.filt.fastq.gz line 1 (expected '>' character)
[lobSTR-3.0.2] 2014-11-21.09:29:34 ProgressMeter: Outputting run statistics

**Comment by trifud** [comment]
I had a similar problem and then I added the `--bam` argument. It seemed to work but at some point I got the same error again:

    [lobSTR-3.0.3] 2015-01-18.22:48:40 ProgressMeter: Processed 10390000 reads 0.0476229 passed detection. 0.0138773 passed alignment.
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ProgressMeter: Processed 10400000 reads 0.0477224 passed detection. 0.0138639 passed alignment.
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ProgressMeter: Processed 10408726 reads
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ProgressMeter: Outputting run statistics
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ERROR: Server not found
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ProgressMeter: Outputting run statistics
    [lobSTR-3.0.3] 2015-01-18.22:48:41 ERROR: Server not found

I am running with the following command: `lobSTR --index-prefix hg19_v3.0.2/lobstr_v3.0.2_hg19_ref/lobSTR_ -f 0209-56f37a74-5a66-4ab4-8e73-84412aa5fdc8.bam --bam --rg-sample foo --rg-lib foo --fft-window-size 24 --fft-window-step 12 --out foo`

What am I doing wrong?

**Comment by mgymrek** [comment]
My guess is this is unrelated to this issue (fastq ID's) and happens because lobSTR attempts at the end of each run to send runtime statistics to us, and it looks like it could not connect to the internet. You can turn this feature off using the ````--noweb``` flag and that should solve this.

The fastq ID issue, if you got that error, was because lobSTR by default expects a fasta file, and in this case you're using a BAM file. You correctly solved this by using the ```--bam``` flag.

**Comment by trifud** [comment]
Thanks! That solved the issue.
