### ISSUE TITLE
Report Q scores in a log scale

### ISSUE THREAD

**Issue by hdashnow** [mgymrek/lobstr-code#66]
It would be awesome if you could report Q scores in a log scale (e.g. Phred-style). I'm finding that for high coverage genomes, most of the Q scores are equal to 1, and so it makes it difficult to distinguish false positives.

**Comment by mgymrek** [comment]
Agreed, this issue has come up many times. I have added a field "PQ", which reports -log10(1-Q), with [this commit](https://github.com/mgymrek/lobstr-code/commit/020a458771679faf74fc9830b40917a4b34fa6e9). The master branch contains this change.
