### ISSUE TITLE
the 

### ISSUE THREAD

**Issue by GuanglinHe1** [mgymrek/lobstr-code#93]
Hello,   
   I have met with a problem when I install this software, that is "make" commond, and the process of make has failed.
 the error as follow:
make  all-recursive
make[1]: Entering directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6'
Making all in m4
make[2]: Entering directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6/m4'
Making all in src
make[2]: Entering directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6/src'
g++ -DHAVE_CONFIG_H -I. -I..   -I../src/ -I../ -I/usr/local/include -I/usr/local/include   -g -O2 -Wall -Wextra -Wswitch-default -Wno-strict-aliasing -pthread -D_GIT_VERSION="\"4.0.6\"" -D_MACHTYPE="\"x86_64\"" -I/usr/include -MT liblobstr_a-AlignmentUtils.o -MD -MP -MF .deps/liblobstr_a-AlignmentUtils.Tpo -c -o liblobstr_a-AlignmentUtils.o `test -f 'AlignmentUtils.cpp' || echo './'`AlignmentUtils.cpp
mv -f .deps/liblobstr_a-AlignmentUtils.Tpo .deps/liblobstr_a-AlignmentUtils.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I../src/ -I../ -I/usr/local/include -I/usr/local/include   -g -O2 -Wall -Wextra -Wswitch-default -Wno-strict-aliasing -pthread -D_GIT_VERSION="\"4.0.6\"" -D_MACHTYPE="\"x86_64\"" -I/usr/include -MT liblobstr_a-BamFileReader.o -MD -MP -MF .deps/liblobstr_a-BamFileReader.Tpo -c -o liblobstr_a-BamFileReader.o `test -f 'BamFileReader.cpp' || echo './'`BamFileReader.cpp
mv -f .deps/liblobstr_a-BamFileReader.Tpo .deps/liblobstr_a-BamFileReader.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I../src/ -I../ -I/usr/local/include -I/usr/local/include   -g -O2 -Wall -Wextra -Wswitch-default -Wno-strict-aliasing -pthread -D_GIT_VERSION="\"4.0.6\"" -D_MACHTYPE="\"x86_64\"" -I/usr/include -MT liblobstr_a-BamPairedFileReader.o -MD -MP -MF .deps/liblobstr_a-BamPairedFileReader.Tpo -c -o liblobstr_a-BamPairedFileReader.o `test -f 'BamPairedFileReader.cpp' || echo './'`BamPairedFileReader.cpp
mv -f .deps/liblobstr_a-BamPairedFileReader.Tpo .deps/liblobstr_a-BamPairedFileReader.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I../src/ -I../ -I/usr/local/include -I/usr/local/include   -g -O2 -Wall -Wextra -Wswitch-default -Wno-strict-aliasing -pthread -D_GIT_VERSION="\"4.0.6\"" -D_MACHTYPE="\"x86_64\"" -I/usr/include -MT liblobstr_a-BWAReadAligner.o -MD -MP -MF .deps/liblobstr_a-BWAReadAligner.Tpo -c -o liblobstr_a-BWAReadAligner.o `test -f 'BWAReadAligner.cpp' || echo './'`BWAReadAligner.cpp
mv -f .deps/liblobstr_a-BWAReadAligner.Tpo .deps/liblobstr_a-BWAReadAligner.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I../src/ -I../ -I/usr/local/include -I/usr/local/include   -g -O2 -Wall -Wextra -Wswitch-default -Wno-strict-aliasing -pthread -D_GIT_VERSION="\"4.0.6\"" -D_MACHTYPE="\"x86_64\"" -I/usr/include -MT liblobstr_a-common.o -MD -MP -MF .deps/liblobstr_a-common.Tpo -c -o liblobstr_a-common.o `test -f 'common.cpp' || echo './'`common.cpp
common.cpp: In function 'bool fexists(const char*)':
common.cpp:195:10: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ifile;
          ^~~~~
Makefile:1954: recipe for target 'liblobstr_a-common.o' failed
make[2]: *** [liblobstr_a-common.o] Error 1
make[2]: Leaving directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6/src'
Makefile:441: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/XiaominYang/biosoftware/lobSTR-4.0.6'
Makefile:373: recipe for target 'all' failed
make: *** [all] Error 2
 
Any help would be greatly appreciated!!

**Comment by gymreklab** [comment]
LobSTR is not actively being supported. I encourage you to check out HipSTR: http://github.com/tfwillems/hipstr which is a more updated tool and performs the same STR genotyping task.

**Comment by GuanglinHe1** [comment]
> LobSTR is not actively being supported. I encourage you to check out HipSTR: [http://github.com/tfwillems/hipstr](https://github.com/tfwillems/hipstr) which is a more updated tool and performs the same STR genotyping task.
